services:
  greenroots-db:
    image: postgres:17
    restart: unless-stopped
    networks:
      - greenroots-network
    volumes:
      - greenroots-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  greenroots-redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - greenroots-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  greenroots-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: ${API_LOCAL_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@greenroots-db:5432/${POSTGRES_DB}
      REDIS_URL: redis://greenroots-redis:6379
      NODE_ENV: development
      JWT_SECRET: ${API_JWT_SECRET}
    ports:
      - ${API_LOCAL_PORT}:${API_LOCAL_PORT}
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - greenroots-network
    depends_on:
      greenroots-db:
        condition: service_healthy
      greenroots-redis:
        condition: service_healthy
    command: npm run docker:dev

  greenroots-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:${API_LOCAL_PORT}
    ports:
      - ${CLIENT_LOCAL_PORT}:5173
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - greenroots-network

networks:
  greenroots-network:

volumes:
  greenroots-db-volume:
