FROM node:22-alpine

WORKDIR /app

ENV DATABASE_URL=postgres://greenroot_test:greenroot_test@postgres-test:5432/greenroot_test

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run db:generate

CMD ["npm", "test"]
